mkdir -p build
cd build

cmake ${CMAKE_ARGS} -DCMAKE_INSTALL_PREFIX=${PREFIX} \
	  -DCMAKE_PREFIX_PATH=${PREFIX} \
	  -DCMAKE_INSTALL_LIBDIR=lib \
	  -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_SHARED_LIBS=ON \
	  -DABSL_USE_EXTERNAL_GOOGLETEST=ON \
	  -DABSL_BUILD_TESTING=ON \
	  -DABSL_BUILD_TEST_HELPERS=ON \
      -GNinja \
	  ..

ninja install
