c_compiler_version:         # [linux and not aarch64]
  - 8                       # [linux and not (s390x or aarch64 or ppc64le)]
  - 8                       # [linux and ppc64le]
  - 8                       # [linux and s390x]
cxx_compiler_version:       # [linux]
  - 8                       # [linux and not (s390x or aarch64 or ppc64le)]
  - 8                       # [linux and ppc64le]
  - 8                       # [linux and s390x]

cxx_compiler:               # [win]
  - 'vs2019'                # [win]
c_compiler:                 # [win]
  - 'vs2019'                # [win]
vc:                         # [win]
  - 16                      # [win]

# abseil now only support MacOS >=10.13, see
# https://github.com/abseil/abseil-cpp#support and
# https://github.com/abseil/abseil-cpp/issues/1513
CONDA_BUILD_SYSROOT:       # [osx and x86]
  - /opt/MacOSX10.13.sdk   # [osx and x86]
macos_min_version:         # [osx and x86]
  - 10.13                  # [osx and x86]