{% set name = "abseil-cpp" %}
{% set version = "20200225.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/abseil/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 0db0d26f43ba6806a8a3338da3e646bb581f0ca5359b3a201d8fb8e4752fd5f8
  patches:
    - clang4_osx_fix.diff  # [osx]
    - osx_framework_fix.diff  # [osx]

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage("abseil-cpp", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]

test:
  commands:
    - test -f $PREFIX/lib/libabsl_base.a  # [not win]
    - if not exist %LIBRARY_LIB%\\absl_base.lib exit 1  # [win]

about:
  home: https://github.com/abseil/abseil-cpp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Abseil Common Libraries (C++)
  description: |
    Abseil is an open-source collection of C++ code (compliant to C++11)
    designed to augment the C++ standard library.
  doc_url: https://github.com/abseil/abseil-cpp
  dev_url: https://github.com/abseil/abseil-cpp

extra:
  recipe-maintainers:
    - njzjz
    - bluescarni
    - xhochy
