travis:
  secure:
    BINSTAR_TOKEN: BveXgm/RzOAZQ6lOUQzePM05/TWw9BBrj06M04PECARf6zEVPr6E2sfw87kMzeZY9cZqPNLePcxZlHqPWQR5fVwGAdgLamnSPfWNbvq7yuSSNNtpRRd23dZFxnPeo3gHcLXrne159pNqbXT2Ecyu8Dtk28IGMATjryxEeHxZLtM6e04VRNcAm/D4o4DQVmLtKRbyS45dLOgSqpLqpg2sU5MUc4JACWqZpDf05l0Z09Y7xctvLuWHB07PkhXu1HGG+gnZd3GZUWc3t/3I5CEXUr/IOvQqHZKdX/dDiKS+S9rJxedjoK9NAGrkBnMOVoJYeA4/IFD1XDKwpH3nlXi5vbR1O4Y8V0PCwXBE8vwjD2RRBTVo6XYogrLpwDYuQqD4YItoJzTVrvQGa1cS/CqUhV8+jILU7A6kxCksIVMfSEvwZ+lm6Xu4obG6tXolpzy5t2gRddltGiMXM2VnsSo0krIrMpTNZHE76K3oTlNAieb/a6eH7YrATXt7jFuJ+c9X2+hEREEqAD4SzWjUE/9LkY9cedYm8wRE0GdqL0Kh8mzByJxYQibbSpBMvpN38V4IjD/xm1z3ibcwfhqLo/dbXoXyQJcp3ygighBEsA6XvP6VlO7WT/4rEnJZS0n2BZRLA+fppfVQhRWx5sfIabeTvax5zgyr8BbfSQATeyQ87dM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
